### ISSUE TITLE
Paper: itSIMPLE: Towards an Integrated Design System for Real Planning Applications

### ISSUE THREAD

**Issue by eg3r** [ForschungsprojektStuttgart/Planung#15]
https://scholar.google.de/scholar?q=Towards+an+Integrated+Design+System+for+Real+Planning+Applications&hl=de&as_sdt=0&as_vis=1&oi=scholart

(das alte paper?) https://www.aaai.org/Papers/ICAPS/2006/ICAPS06-059.pdf

github:
https://github.com/tvaquero/itsimple

itSimple 2.0:
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.583.39&rep=rep1&type=pdf

**Comment by eg3r** [comment]
"itSIMPLE [86–89] is an IDE for modelling planning domains. The tool was
designed to support users during the construction of a planning domain appli-
cation mainly in the initial stages of the design life cycle. The stages include
processes such as domain specifcation, modelling, analysis, model testing and
maintenance, all of which are crucial to the success of the application.
itSIMPLE started by basing itself around the semi-formal specifcation lan-
guage, UML [23], which is a well-known diagrammatic language. With the tool
being aimed at both those who are familiar and unfamiliar with AI planning us-
ing a more general specifcation language keeps the barrier to entry minimal. "

[Zitat aus: https://research.tees.ac.uk/ws/portalfiles/portal/9820238/Acquiring_Planning_Models_from_Narrative_Synopses.pdf ]

**Comment by izallex** [comment]
[Uploading itSIMPLE.pdf…]()

**Comment by izallex** [comment]
[itSIMPLE.pdf](https://github.com/ForschungsprojektStuttgart/Planung/files/7617451/itSIMPLE.pdf)
