### ISSUE TITLE
1st Draft

### ISSUE THREAD

**Issue by AmelVatic** [ForschungsprojektStuttgart/Planung#6]

**Comment by izallex** [comment]
[Domain.pdf](https://github.com/ForschungsprojektStuttgart/Planung/files/7735561/Domain.pdf)
[Object Types.pdf](https://github.com/ForschungsprojektStuttgart/Planung/files/7735562/Object.Types.pdf)
[Predicates.pdf](https://github.com/ForschungsprojektStuttgart/Planung/files/7735565/Predicates.pdf)
[Actions.pdf](https://github.com/ForschungsprojektStuttgart/Planung/files/7735566/Actions.pdf)
[Axioms.pdf](https://github.com/ForschungsprojektStuttgart/Planung/files/7735569/Axioms.pdf)
[Constants.pdf](https://github.com/ForschungsprojektStuttgart/Planung/files/7735570/Constants.pdf)
[Numeric- Fluents, Expressions, Effect Operations.pdf](https://github.com/ForschungsprojektStuttgart/Planung/files/7735571/Numeric-.Fluents.Expressions.Effect.Operations.pdf)
[Durative Actions.pdf](https://github.com/ForschungsprojektStuttgart/Planung/files/7735574/Durative.Actions.pdf)

**Comment by izallex** [comment]
Ausdrücke (logisch und numerisch) wahrscheinlich besser durch Bäume.
